commerce_payment.commerce_payment_gateway.plugin.sberbank_acquiring:
  type: commerce_payment_gateway_configuration
  mapping:
    username:
      type: string
      label: 'Username'
    password:
      type: string
      label: 'Password'