commerce_payment.commerce_payment_gateway.plugin.sberbank_acquiring:
  type: commerce_payment_gateway_configuration
  mapping:
    username:
      type: string
      label: 'Username'
    password:
      type: string
      label: 'Password'
    order_id_prefix:
      type: string
      label: 'Order ID prefix'
    order_id_suffix:
      type: string
      label: 'Order ID suffix'